== Developpers: How to setup your environment and be ready to code

You can either use CQFD to run testing tools in a container or install the tools on your machine.
CQFD is better for testing quickly but if you plan to modify the code and commit,
you would probably prefer local installation which integrate with pre-commit.

=== Nothing to install, all in CQFD

.Already used to CQFD? Go ahead, else read this setup tutorial
[%collapsible]
====

* Install Docker by following the official
  documentation: https://docs.docker.com/engine/install/

Make sure that Docker does not require `sudo`.

Please use the following commands to add your user account to the `docker`
group:

[bash]
----
  $ sudo groupadd docker
  $ sudo usermod -aG docker $USER
----

Log out and log back in, so that your group membership can be re-evaluated.

* Install cqfd:

[bash]
----
  $ git clone https://github.com/savoirfairelinux/cqfd.git
  $ cd cqfd
  $ sudo make install
----

The project page on GitHub (https://github.com/savoirfairelinux/cqfd[link])
contains detailed information on usage and installation.

====

The first step with `cqfd` is to create the build container. Do this using:

[bash]
----
  $ cqfd init
----

NOTE: The step above is only required once, as once the container image has been
created on your machine, it will become persistent. Further calls to `cqfd init`
will do nothing, unless the container definition (`.cqfd/docker/Dockerfile`) has
changed in the source tree.

=== Install and setup locally without CQFD

- Ensure to have make, Docker, Python 3 and Node.js with NPM installed on your machine.
- Clone the project.
- Run `pip install -r requirements-dev.txt` to install the backend dev dependencies.
- Run `pre-commit install` to enable pre-commit (code quality and linter).
- Move to frontend and install npm dev dependencies +
`cd frontend && npm install --include=dev`
- Done ! You are ready to code.

== Commands used to manage this repository

=== Unit and Integration testing

* Run all the Python and Node.js tests with:

[bash]
----
  $ cqfd -b test
  # or
  $ make test
----

* You can also run only backend or frontend tests (not available with CQFD):

[bash]
----
  $ make test_backend
  $ make test_frontend
----

* To test Docker image build, you can use:

----
  $ export BUILD_TAG="$(pwgen -n 12 -1)"
  $ make docker_build docker_test docker_clean
----

=== Publishing new version

1. Identify which version is next and determine which one you want to create. +
Support Semantic Versioning 2.0.0 (https://semver.org/), with a leading `v` and support metadata. +
For example, `v1.2.3` or `v1.2.3+build.4`.

2. Run the following command to create a new tag: +
`bin/release_tag.sh v1.0.0-rc.1` (using your determined tag).

3. The script will update files with the new version, then will ask you if you want to make a new commit or amend the last one. +
**Before you choose, it is recommended to check the changes** you are about to commit. +
Use Ctrl+C to cancel the script if changes is not corresponding to what you wanted.

4. After commit validation, it run a `git review` which, at most case, will ask you to confirm with `yes`. +
You can Ctrl+C to cancel the script if you don't want to push the commit.

5. The script will ask you a message for creating the tag.
**If you don't want to create a tag now (example: you have pending review), make Ctrl+C to cancel the script.** +
If you confirm with empty text, it create tag with `Release v*.*.*` message.

6. The script will push the tag to the remote repository. This will trigger the Jenkins pipeline to build and publish the new docker image.

=== Linter, Unit tests, Code coverage and Code Quality

* Python Backend (Python3 + Flask)
** Linter: `flake8`
** Type check: `mypy --config-file tox.ini`
** Unit tests: `pytest`
** Code coverage in terminal: `pytest --cov=src`
** Code coverage as HTML: `pytest --cov-report html --cov=src`
* Web Frontend (Typescript + React)
** Run with `npm run dev`
** Build with `npm run build`
** Unit test: `npm run test` (use jest + testing-library/react)
** Linter: `npm run lint` (use ESlinter)
** Code coverage: `npm run coverage`
* Build documentation: `asciidoctor-pdf README.adoc`

NOTE: You can run all the tools using `make test` command. If you have installed pre-commit,
flake8 will also run before every commit to ensure linting is good.
If you use CQFD, running `cqfd -b test` will run all the tests (equivalent to `make test`).

=== Pre commit

To ensure a good quality of code, we use pre-commit to run flake8 before commiting.
To install pre-commit, run `pip install pre-commit`.
Then, to enable pre-commit, run `pre-commit install`.
