= Developper's Guide
Savoir-faire Linux
:url-repo: https://github.com/savoirfairelinux/vulnscout
:source-highlighter: highlight.js
:toc:
:icons: font
:icon-set: fa


== icon:terminal[] Developing VulnScout

=== Requirements

NVM 22 is required to develop on VulnScout without any issues.
Installation guide for NVM : https://github.com/nvm-sh/nvm[nvm]

[source,bash]
----
nvm install 22
nvm use 22
----

=== Modify the frontend

By default, the _/frontend_ directory is not mounted in a volume with the container. To visualise frontend modifications, you will need to run VulnScout in development mode.
To do so, you can run the following command:

[source,bash]
----
./start-example.sh --dev
----

== icon:check[] Testing the project

We use CQFD to run testing tools in a container.

=== Quick Setup with CQFD

==== Step 1: Setup CQFD and Docker

* Install Docker: https://docs.docker.com/engine/install/

Make sure Docker runs without requiring `sudo`. To do so, add your user to the `docker` group:

[source,bash]
----
sudo groupadd docker
sudo usermod -aG docker $USER
----

Log out and log back in to apply the changes.

* Install CQFD:

[source,bash]
----
git clone https://github.com/savoirfairelinux/cqfd.git
cd cqfd
sudo make install
----

For more information, visit the CQFD GitHub repository: https://github.com/savoirfairelinux/cqfd

==== Step 2: Initialise CQFD for this project

Once installed, initialise the container image:

[source,bash]
----
cqfd init
----

NOTE: This only needs to be done once, unless the container definition (`.cqfd/docker/Dockerfile`) is modified.

==== Step 3: Run all the tests with CQFD

To run all tests using CQFD, execute the following command:

[source,bash]
----
cqfd
----

Also, you can run the tests separately:

[source,bash]
----
cqfd -b test_backend
cqfd -b test_frontend
----

=== Testing the Docker image

You can test the Docker image using the provided `tests` Makefile.
To build and test the Docker image, run:

[source,bash]
----
export BUILD_TAG="$(pwgen -n 12 -1)"
make -C tests docker_build docker_test docker_clean
----

== icon:code[] Code quality and linting

=== Python backend (Flask)

- Linter: `flake8`
- Type checking (from tests/ folder): `mypy --config-file tox.ini`
- Unit tests: `pytest`
- Coverage (terminal): `pytest --cov=src`
- Coverage (HTML): `pytest --cov-report html --cov=src`

=== Frontend (React + TypeScript)

- Dev server: `npm run dev`
- Build: `npm run build`
- Unit tests: `npm run test` (uses Jest + Testing Library)
- Linter: `npm run lint` (ESLint)
- Coverage report: `npm run coverage`

NOTE: Running `make -C tests test` will execute all linters and tests. If `pre-commit` is installed, `flake8` will also run on every commit.
With CQFD, use `cqfd -b test` to run the full suite.

=== Pre-commit hook

We use `pre-commit` to automatically run `flake8` before every commit.

To enable it:

[source,bash]
----
pip install pre-commit
pre-commit install
----

This helps enforce code quality and consistency across all contributions.