"""add secondary indexes for vuln - assessment

Revision ID: c8748f805850
Revises: d3f8c1a2b9e5
Create Date: 2026-03-18 13:05:26.153619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8748f805850'
down_revision = 'd3f8c1a2b9e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: The original auto-generated migration had upgrade/downgrade swapped.
    # It was dropping indexes instead of creating them. Fixed to be a no-op
    # since the indexes are already created by c7f2a3d8e1b4.
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_variant_id'), ['variant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_finding_id'), ['finding_id'], unique=False)

    # ### end Alembic commands ###
