"""add secondary indexes for vuln - assessment

Revision ID: c8748f805850
Revises: d3f8c1a2b9e5
Create Date: 2026-03-18 13:05:26.153619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8748f805850'
down_revision = 'd3f8c1a2b9e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_finding_id'))
        batch_op.drop_index(batch_op.f('ix_assessments_variant_id'))

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_package_id'))
        batch_op.drop_index(batch_op.f('ix_findings_vulnerability_id'))

    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metrics_vulnerability_id'))

    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_finding_id'))
        batch_op.drop_index(batch_op.f('ix_observations_scan_id'))

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packages_name_version'))

    with op.batch_alter_table('sbom_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sbom_documents_scan_id'))

    with op.batch_alter_table('sbom_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sbom_packages_package_id'))

    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_variant_id'))

    with op.batch_alter_table('time_estimates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_estimates_finding_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_estimates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_estimates_finding_id'), ['finding_id'], unique=False)

    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scans_variant_id'), ['variant_id'], unique=False)

    with op.batch_alter_table('sbom_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sbom_packages_package_id'), ['package_id'], unique=False)

    with op.batch_alter_table('sbom_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sbom_documents_scan_id'), ['scan_id'], unique=False)

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packages_name_version'), ['name', 'version'], unique=False)

    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observations_scan_id'), ['scan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_finding_id'), ['finding_id'], unique=False)

    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metrics_vulnerability_id'), ['vulnerability_id'], unique=False)

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_vulnerability_id'), ['vulnerability_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_package_id'), ['package_id'], unique=False)

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_variant_id'), ['variant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_finding_id'), ['finding_id'], unique=False)

    # ### end Alembic commands ###
