# Copyright (C) 2026 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: GPL-3.0-only

from ..models import Package
from .yocto_base import YoctoBase


class YoctoVex(YoctoBase):
    """Parser for the Yocto VEX JSON format produced by the generate_vex bbclass.

    The format is structurally similar to the yocto cve-check JSON but carries
    additional fields generated by the OpenEmbedded ``vex.bbclass``:

    Package-level extras
    --------------------
    - ``layer``      : Yocto layer that owns the recipe (e.g. ``meta``,
                       ``meta-oe``).  Stored as ``Package.supplier``.
    - ``cpes``       : List of CPE strings built from ``CVE_PRODUCT`` /
                       ``CVE_VERSION``.  Used directly instead of generating
                       generic CPEs.
    - ``products``   : List of ``{product, cvesInRecord}`` dicts.  Each
                       product name is used to build an additional CPE that
                       is added to the package.

    Issue-level extras (handled by :class:`YoctoBase`)
    ---------------------------------------------------
    - ``detail``     : Human-readable detail string for the CVE status
                       (e.g. ``"fixed-version: Fixed externally"``).
                       Stored in ``Assessment.status_notes``.
    - ``description``: Free-text justification recorded as a SBOM observation
                       keyed ``"Yocto VEX Description"``.
    - ``patch-file`` : Path/URL of the patch resource.  Stored in
                       ``Vulnerability.patch_url`` via ``add_advisory()``.
    - ``vector``     : Short CVSS attack-vector token (e.g. ``AV:N``).
                       Stored in ``Vulnerability.attack_vector``.
    - ``vectorString``: Full CVSS vector string used to build CVSS objects.
    """

    _SOURCE_TAG = "yocto_vex"
    _PATCHED_LABEL = "Yocto VEX reported vulnerability as Patched"
    _IGNORED_LABEL = "Yocto VEX reported vulnerability as Ignored"
    _SBOM_KEY = "Yocto VEX Description"

    def _build_package(self, pkg: dict) -> Package:
        layer = pkg.get("layer", "")
        version = pkg.get("version", "")

        # Use the CPEs provided by the VEX format directly.
        cpes = list(pkg.get("cpes", []))

        # Also derive CPEs from the products list so that every
        # product/version combination becomes searchable.
        for product_entry in pkg.get("products", []):
            product_name = product_entry.get("product", "")
            if product_name:
                derived_cpe = f"cpe:2.3:a:*:{product_name}:{version}:*:*:*:*:*:*:*"
                if derived_cpe not in cpes:
                    cpes.append(derived_cpe)

        package = Package(pkg["name"], version, cpes, [], supplier=layer)
        package.generate_generic_purl()
        return package
