"""add project variant scan sbom_document tables

Revision ID: c70f79fa555a
Revises: 
Create Date: 2026-03-13 09:55:28.210625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70f79fa555a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_projects_name')
    )
    op.create_table('variants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'project_id', name='uq_variants_name_project')
    )
    op.create_table('scans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sbom_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sbom_documents')
    op.drop_table('scans')
    op.drop_table('variants')
    op.drop_table('projects')
    # ### end Alembic commands ###
