name: Run Vulnscout Tests

on: [push, pull_request]

jobs:
  tests:
    name: ${{ matrix.target }} Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [Backend, Frontend, CI, Schema, Docker, Podman]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install cqfd on the CI
        if: matrix.target != 'Docker' && matrix.target != 'Podman'
        run: |
          git clone https://github.com/savoirfairelinux/cqfd.git
          cd cqfd
          sudo make install

      - name: Init cqfd container on the project
        if: matrix.target != 'Docker' && matrix.target != 'Podman'
        run: cqfd init

      - name: Install Podman
        if: matrix.target == 'Podman'
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Run Backend Tests in the container
        if: matrix.target == 'Backend'
        run: cqfd -b test_backend

      - name: Run Frontend Tests in the container
        if: matrix.target == 'Frontend'
        run: cqfd -b test_frontend

      - name: Run CI Tests in the container
        if: matrix.target == 'CI'
        run: cqfd -b test_ci

      - name: Run Schema Conformity Tests in the container
        if: matrix.target == 'Schema'
        run: cqfd -b validate_sbom

      - name: Docker Build
        if: matrix.target == 'Docker'
        run: BUILD_TAG=${{ github.sha }} make -C tests docker_build

      - name: Docker Test
        if: matrix.target == 'Docker'
        run: BUILD_TAG=${{ github.sha }} make -C tests docker_test

      - name: Docker Clean
        if: ${{ matrix.target == 'Docker' && always() }}
        run: BUILD_TAG=${{ github.sha }} make -C tests docker_clean

      - name: Podman Build
        if: matrix.target == 'Podman'
        run: BUILD_TAG=${{ github.sha }} make -C tests podman_build

      - name: Podman Test
        if: matrix.target == 'Podman'
        run: BUILD_TAG=${{ github.sha }} make -C tests podman_test

      - name: Podman Clean
        if: ${{ matrix.target == 'Podman' && always() }}
        run: BUILD_TAG=${{ github.sha }} make -C tests podman_clean