= Vulnerabilities Report
Company name
2024-07-15
:toc:

== Legal Notice

[.text-justify]
This report is a summary of the vulnerabilities found in the project. Scan was made on 2024-07-15 at 11:02:45 and export of this report was made on 2024-07-15 at 11:18:12. Keep in mind that this report is not exhaustive and may not contain all vulnerabilities found in the project. Also, new vulnerabilities are discovered every day and thus the precision and accuracy of this report will decrease over time.

== Summary

Number of vulnerabilities found: **{{ vulnerabilities | as_list | length }}**

They are classified as follow:

[cols="2,1,1,1,1,1,1"]
[.text-justify]
|===
^.^| Status ^.^| Critical ^.^| High ^.^| Medium ^.^| Low ^.^| Unknown ^.^| Total

^.^| Pending investigation
^.^| {{ vulnerabilities | as_list | status_pending | severity("critical") | length }}
^.^| {{ vulnerabilities | as_list | status_pending | severity("high") | length }}
^.^| {{ vulnerabilities | as_list | status_pending | severity("medium") | length }}
^.^| {{ vulnerabilities | as_list | status_pending | severity("low") | length }}
^.^| {{ vulnerabilities | as_list | status_pending | severity("unknown") | length }}
^.^| **{{ vulnerabilities | as_list | status_pending | length }}**

^.^| Confirmed and exploitable
^.^| {{ vulnerabilities | as_list | status_affected | severity("critical") | length }}
^.^| {{ vulnerabilities | as_list | status_affected | severity("high") | length }}
^.^| {{ vulnerabilities | as_list | status_affected | severity("medium") | length }}
^.^| {{ vulnerabilities | as_list | status_affected | severity("low") | length }}
^.^| {{ vulnerabilities | as_list | status_affected | severity("unknown") | length }}
^.^| **{{ vulnerabilities | as_list | status_affected | length }}**

^.^| Fixed
^.^| {{ vulnerabilities | as_list | status_fixed | severity("critical") | length }}
^.^| {{ vulnerabilities | as_list | status_fixed | severity("high") | length }}
^.^| {{ vulnerabilities | as_list | status_fixed | severity("medium") | length }}
^.^| {{ vulnerabilities | as_list | status_fixed | severity("low") | length }}
^.^| {{ vulnerabilities | as_list | status_fixed | severity("unknown") | length }}
^.^| **{{ vulnerabilities | as_list | status_fixed | length }}**

^.^| Ignored or false positive
^.^| {{ vulnerabilities | as_list | status_ignored | severity("critical") | length }}
^.^| {{ vulnerabilities | as_list | status_ignored | severity("high") | length }}
^.^| {{ vulnerabilities | as_list | status_ignored | severity("medium") | length }}
^.^| {{ vulnerabilities | as_list | status_ignored | severity("low") | length }}
^.^| {{ vulnerabilities | as_list | status_ignored | severity("unknown") | length }}
^.^| **{{ vulnerabilities | as_list | status_ignored | length }}**
|===

You will find below the vulnerabilities found, starting by open / active vulnerabilities and in the next section thoses who are closed.
All vulnerabilities are classed by the date of last change.

<<<

== Open vulnerabilities (classed as pending review or exploitable)

{% for vuln in vulnerabilities | as_list | status_active | sort_by_epss | sort_by_last_modified %}

[{{vuln.last_assessment.timestamp | print_iso8601}}] **{{ vuln.id }} ({{ vuln.severity.severity | capitalize }}) - EPSS: {{ "%.2f" | format(vuln.epss.score | float * 100) }} %**

Impacts following packages: {{' & '.join(vuln.packages)}} +
Reference: {{ vuln.datasource or vuln.urls[0] or "No sources found" }}

**History of assessments:**
{% for assess in vuln.assessments %}
* [{{assess.timestamp | print_iso8601}}] {{assess.status}} {{assess.justification or ""}}
{%- if assess.status_notes != '' %}
** Notes: {{assess.status_notes}}
{%- endif %}
{%- if assess.impact_statement != '' %}
** Impact statement: {{assess.impact_statement}}
{%- endif %}
{%- if assess.workaround != '' %}
** Workaround: {{assess.workaround}}
{%- endif %}
{%- endfor %}

'''

{%- endfor %}

<<<

== Closed vulnerabilities (classed as patched or ignored)

{% for vuln in vulnerabilities | as_list | status_inactive | sort_by_epss | sort_by_last_modified %}

[{{vuln.last_assessment.timestamp | print_iso8601}}] **{{ vuln.id }} ({{ vuln.severity.severity | capitalize }}) - EPSS: {{ "%.2f" | format(vuln.epss.score | float * 100) }} %**

Impacts following packages: {{' & '.join(vuln.packages)}} +
Reference: {{ vuln.datasource or vuln.urls[0] or "No sources found" }}

**History of assessments:**
{% for assess in vuln.assessments %}
* [{{assess.timestamp | print_iso8601}}] {{assess.status}} {{assess.justification or ""}}
{%- if assess.status_notes != '' %}
** Notes: {{assess.status_notes}}
{%- endif %}
{%- if assess.impact_statement != '' %}
** Impact statement: {{assess.impact_statement}}
{%- endif %}
{%- if assess.workaround != '' %}
** Workaround: {{assess.workaround}}
{%- endif %}
{%- endfor %}

'''

{%- endfor %}
