= Vulnerabilities Report
Company name
2024-07-15

== Legal Notice

This report is a summary of the vulnerabilities found in the project. Scan was made on 2024-07-15 at 11:02:45 and export of this report was made on 2024-07-15 at 11:18:12. Keep in mind that this report is not exhaustive and may not contain all vulnerabilities found in the project. Also, new vulnerabilities are discovered every day and thus the precision and accuracy of this report will decrease over time.

== Summary

Number of vulnerabilities found: {{ vulnerabilities | as_list | length }}
They are classified as follow:
* {{ vulnerabilities | as_list | status_pending | length }} Pending investigation
** {{ vulnerabilities | as_list | status_pending | severity("critical") | length }} Critical
** {{ vulnerabilities | as_list | status_pending | severity("high") | length }} High
** {{ vulnerabilities | as_list | status_pending | severity("medium") | length }} Medium
** {{ vulnerabilities | as_list | status_pending | severity("low") | length }} Low
** {{ vulnerabilities | as_list | status_pending | severity("unknown") | length }} Unknown

* {{ vulnerabilities | as_list | status_affected | length }} Confirmed and exploitable
** {{ vulnerabilities | as_list | status_affected | severity("critical") | length }} Critical
** {{ vulnerabilities | as_list | status_affected | severity("high") | length }} High
** {{ vulnerabilities | as_list | status_affected | severity("medium") | length }} Medium
** {{ vulnerabilities | as_list | status_affected | severity("low") | length }} Low
** {{ vulnerabilities | as_list | status_affected | severity("unknown") | length }} Unknown

* {{ vulnerabilities | as_list | status_fixed | length }} Fixed
** {{ vulnerabilities | as_list | status_fixed | severity("critical") | length }} Critical
** {{ vulnerabilities | as_list | status_fixed | severity("high") | length }} High
** {{ vulnerabilities | as_list | status_fixed | severity("medium") | length }} Medium
** {{ vulnerabilities | as_list | status_fixed | severity("low") | length }} Low
** {{ vulnerabilities | as_list | status_fixed | severity("unknown") | length }} Unknown

* {{ vulnerabilities | as_list | status_ignored | length }} Ignored or false positive
** {{ vulnerabilities | as_list | status_ignored | severity("critical") | length }} Critical
** {{ vulnerabilities | as_list | status_ignored | severity("high") | length }} High
** {{ vulnerabilities | as_list | status_ignored | severity("medium") | length }} Medium
** {{ vulnerabilities | as_list | status_ignored | severity("low") | length }} Low
** {{ vulnerabilities | as_list | status_ignored | severity("unknown") | length }} Unknown

== Most critical vulnerabilities

The following list use EPSS ranking to outline the vulnerabilities which are most used. The EPSS ranking is a metric that takes into account the number of known exploits, the ease of exploitation, the impact of the vulnerability, and the availability of a fix.

{% for vuln in vulnerabilities | as_list | status_active | sort_by_epss | epss_score(5) | limit(15) %}

** {{ vuln.id }} ({{ vuln.severity.severity | capitalize }}) - EPSS: {{ "%.2f" | format(vuln.epss.score | float * 100) }} %**
{{ vuln.texts["description"] or vuln.texts["summary"] }}

{% endfor %}
